name: CI

on:
  push:
    branches: [ main ]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: JDK environment
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'

      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.0'
        channel: 'stable'
      - run: flutter --version

      #- name: Build Artifact
      #  id: buildAllApks
      #  uses: gradle/gradle-build-action@v2.1.0
      #  with:
      #    gradle-version: current
      #    arguments: assembleRelease
      #    build-root-directory: ./frontend

      #- name: Sign App
      #  id: signApp
      #  uses: r0adkll/sign-android-release@v1
      #  with:
      #    releaseDirectory: ./frontend/app/build/outputs/apk/release
      #    signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      #    alias: ${{ secrets.KEYALIAS }}
      #    keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
      #    keyPassword: ${{ secrets.KEY_PASSWORD }}
      #  env:
      #    BUILD_TOOLS_VERSION: "30.0.3"

      #- name: Upload App
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: Release artifact
      #    path: ./frontend/app/build/outputs/apk/release/app-artifact-*.apk